import random
import win32com.client as wincl
import csv
import time
import numpy as np
from ffpyplayer.player import MediaPlayer
import numpy as np
import cv2


"""
NOTES

D.E.B.R.A.
Definitely Effective Bingo Reciting Application

Some code for playing with voices if I get to it

vcs = spk.GetVoices()
print(vcs.Item(speaker_number) .GetAttribute("Name"))
spk.Voice
spk.SetVoice(vcs.Item(speaker_number))

"""

class DEBRA:
    def __init__(self, toread, encoding = None):
        # DEBRA("standard.csv") or DEBRA("upworthy.csv", encoding = 'utf-8')
        # Expects a CSV with two columns, 'call' and 'number'
        # As generated by scrape_v1

        self.tocall = list(range(1, 91, 1))
        self.called = []
        self.speak = wincl.Dispatch("SAPI.SpVoice")
        self.headers = ['number', 'call']
        self.filename = toread
        self.encoding = encoding

    def progbar(self, num, tot):
        eq = round(((tot - num) / tot) * 20)
        bar = ["="] * 20

        for e, i in enumerate(bar):
            if (e + 1) >= eq:
                bar[e] = " "

        return "[" + "".join(bar) + "]"

    def genNum(self):
        i = random.randint(1, len(self.tocall))
        
        try:
            call = self.tocall[i]
        except IndexError:
            call = self.tocall[0]

        self.tocall.remove(call)
        self.called.append(call)

        return call

    def callNum(self, show = False):
        num = str(self.genNum())
        tosay = num + ". " + "That's " + num + ". "#

        with open(self.filename, 'r', encoding = self.encoding) as csvfile:
            f = csv.DictReader(csvfile, fieldnames = self.headers)
            for row in f:
                if row['number'] == num:
                    tosay = num + "  . " + row['call'] + ". " + num + ". "
                    break

        if show == True:
            print(tosay)

        self.speak.Speak(tosay)
        print(self.progbar(len(self.tocall), 90))

    def autoPilot(self, secs = 3, show = False):
        try:
            while True:
                self.callNum(show)
                time.sleep(secs)
        except KeyboardInterrupt:
            return

    def say(self, tosay):
        self.speak.Speak(tosay)

    def justCalled(self, ind = None):
        if ind == None:
            self.say("I've called" + ", ".join(str(i) for i in self.called))
        elif ind > (len(self.called) - 1):
            self.say("I've called" + ", ".join(str(i) for i in self.called))
        else:
            ind = -1 * ind
            self.say("I've just called" + ", ".join(str(i) for i in self.called[ind:]))


    def intro(self):
        toread = "Hello! I am DEBRA, the Definitely Effective Bingo Reciting Application. Nice to meet you!"
        toread2 = "Because of the way I make noise, I'm afraid you won't be able to hear my creator, Will, while I'm in use. He's not dead though! Ha, Ha, Ha."
        toread3 = "If you need my calls slowed down, sped up, or would like them written out, just let me know. Will will help me get it done."
        toread4 = "Are you ready to play bingo?"
        yes = "Great. Let's begin."
        no = "Disappointing. You have been placed on the list. Are you sure you're not ready to play bingo?"
        other = "I can't hear you. I said are you ready to play bingo?"

        self.speak.Speak(toread)
        self.speak.Speak(toread2)
        self.speak.Speak(toread3)
        self.speak.Speak(toread4)

        while True:
            userin = input('Y/N: ').lower()
            if userin == "y":
                self.speak.Speak(yes)
                return
            elif userin == "n":
                self.speak.Speak(no)
            else:
                self.speak.Speak(other)

    def line(self):
        toread = "Who's got a line?"
        comeon = "Give me your name or I'll post your credit card details on Twitter."
        
        self.speak.Speak(toread)

        while True:
            userin = input('Enter name: ')
            if userin != "":
                bye = "Well done, " + userin + ". I don't know what you've won, but you've won it."
                self.speak.Speak(bye)
                return
            else:
                self.speak.Speak(comeon)

    def fullHouse(self):
        toread = "Was that a full house? Give me your name!"
        comeon = "Come on, what could I do with your name? Bingo bots can't deepfake videos of you saying how much you love the Cheeky Girls."
        
        self.speak.Speak(toread)

        while True:
            userin = input('Enter name: ')
            if userin != "":
                bye = "Well done, " + userin + ". A full house! Imagine all the things you can do with it."
                self.speak.Speak(bye)
                return
            else:
                self.speak.Speak(comeon)

    def outro(self):
        toread = "Congratulations, bingo winner! What's your name?"
        comeon = "Very wise. Never reveal personal information to a stranger, no matter how beautiful. But can you just make up a name?"

        self.speak.Speak(toread)
        
        while True:
           userin = input('Enter name: ')
           if userin != "":
               bye = "Well done, " + userin + ". Please be nice to your newly-established inferiors. I've been DEBRA, the Definitely Effective Bingo Reciting Application. Bye bye!"
               self.speak.Speak(bye)
               break
           else:
               self.speak.Speak(comeon)

        player = MediaPlayer('udidit2-lofi.mp4')
        val = ''

        while val != 'eof':
            frame, val = player.get_frame()
            if val != 'eof' and frame is not None:
                img, t = frame
                arr = np.uint8(np.asarray(list(img.to_bytearray()[0])).reshape(540,960,3))
                cv2.imshow('u did it', arr)

                if cv2.waitKey(25) & 0xFF == ord('q'):
                    cv2.destroyAllWindows()
                    break
